import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main">
        <h1 className="tourney-font title">HEATSTROKE</h1>
      </div>

      {/*STYLESHEET*/}
      <style jsx>{`
        .main {
          height: 100vh;
          background-image: url("https://radarpena.disway.id/upload/0536dd127748273b75732b12d1504d4c.jpg");
          background-size: cover;
          background-position: center;
          display: flex;
        }

        .title {
          font-size: 180px;
          color: white;
          margin: auto;
        }

        @media (max-width: 1024px) {
          .title {
            font-size: 120px;
          }
        }

        @media (max-width: 768px) {
          .title {
            font-size: 80px;
          }
        }

        @media (max-width: 480px) {
          .title {
            font-size: 50px;
          }
        }
      `}</style>
    </>
  );
}
